#!/usr/bin/env python3
"""Preview or apply marker-delimited SDLC metadata to linked GitHub issues."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import sys

from github import Auth, Github
from github.GithubException import GithubException, UnknownObjectException

from traceability import ROOT, load_manifest

START = "<!-- sdlc-sync:start -->"
END = "<!-- sdlc-sync:end -->"
STATUS_LABEL = {
    "draft": "status:proposed",
    "proposed": "status:proposed",
    "needs-review": "status:needs-review",
    "approved": "status:ready",
    "in-progress": "status:in-progress",
    "done": "status:done",
    "blocked": "status:blocked",
    "obsolete": "status:needs-review",
}


def _replace_block(body: str, block: str) -> str:
    if START in body and END in body:
        before, remainder = body.split(START, 1)
        _, after = remainder.split(END, 1)
        return f"{before.rstrip()}\n\n{block}\n{after.lstrip()}".rstrip() + "\n"
    return f"{body.rstrip()}\n\n{block}\n".lstrip()


def _digest(path: str | None) -> str:
    if not path:
        return "not-file-backed"
    data = (ROOT / path).read_bytes()
    return f"sha256:{hashlib.sha256(data).hexdigest()}"


def _managed_block(
    item: dict, repository: str, default_branch: str
) -> str:
    path = item.get("path")
    if path:
        target = f"https://github.com/{repository}/blob/{default_branch}/{path}"
        artifact = f"[`{item['id']}`]({target})"
    else:
        artifact = f"`{item['id']}`"
    upstream = ", ".join(f"`{value}`" for value in item.get("upstream", [])) or "None"
    return "\n".join(
        [
            START,
            "### Managed SDLC metadata",
            "",
            f"- Artifact: {artifact}",
            f"- Kind: `{item['kind']}`",
            f"- Status: `{item['status']}`",
            f"- Upstream: {upstream}",
            f"- Revision: `{_digest(path)}`",
            "",
            "_Generated by `scripts/sdlc/sync_issues.py`; edit the artifact or "
            "manifest, not this block._",
            END,
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    parser.add_argument(
        "--repository", default=os.environ.get("GITHUB_REPOSITORY", "")
    )
    parser.add_argument("--default-branch", default="main")
    args = parser.parse_args()

    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GITHUB_PAT")
    if not args.repository or not token:
        print("Error: repository and GITHUB_TOKEN/GITHUB_PAT are required.", file=sys.stderr)
        return 2
    if args.apply and os.environ.get("SDLC_SYNC_APPROVED", "").lower() != "true":
        print("Error: --apply requires SDLC_SYNC_APPROVED=true.", file=sys.stderr)
        return 2

    try:
        artifacts = load_manifest()
        repo = Github(auth=Auth.Token(token), timeout=20).get_repo(args.repository)
        drift = False
        for artifact_id in sorted(artifacts):
            item = artifacts[artifact_id]
            number = item.get("github_issue")
            if number is None:
                continue
            issue = repo.get_issue(number)
            desired_body = _replace_block(
                issue.body or "",
                _managed_block(item, args.repository, args.default_branch),
            )
            current_status = {
                label.name for label in issue.labels if label.name.startswith("status:")
            }
            desired_status = {STATUS_LABEL[item["status"]]}
            changed = desired_body != (issue.body or "") or current_status != desired_status
            if not changed:
                print(f"#{number} {artifact_id}: synchronized")
                continue
            drift = True
            if args.apply:
                issue.edit(body=desired_body)
                for label in current_status - desired_status:
                    issue.remove_from_labels(label)
                for label in desired_status - current_status:
                    issue.add_to_labels(label)
                print(f"#{number} {artifact_id}: updated")
            else:
                print(
                    f"#{number} {artifact_id}: would update managed metadata "
                    f"and set {next(iter(desired_status))}"
                )
        if args.check and drift:
            return 1
        return 0
    except (GithubException, UnknownObjectException, OSError, ValueError) as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
